### ISSUE TITLE
PostCSS plugin postcss-nested requires PostCSS 8.

### ISSUE THREAD

**Issue by mujehoxe** [adamwathan/cra-tailwind-3#1]
yarn run v1.22.15
$ concurrently "npm run start:css" "react-scripts start"
[0] 
[0] > cra-tailwind-3@0.1.0 start:css
[0] > tailwindcss -o src/tailwind.css --watch
[0] 
[0] 
[0] Rebuilding...
[0] Error: PostCSS plugin postcss-nested requires PostCSS 8.
[0] Migration guide for end-users:
[0] https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
[0]     at Processor.normalize (/home/o/Documents/js/cra-tailwind-3/node_modules/postcss/lib/processor.js:167:15)
[0]     at new Processor (/home/o/Documents/js/cra-tailwind-3/node_modules/postcss/lib/processor.js:56:25)
[0]     at Object.postcss [as default] (/home/o/Documents/js/cra-tailwind-3/node_modules/postcss/lib/postcss.js:55:10)
[0]     at /home/o/Documents/js/cra-tailwind-3/node_modules/tailwindcss/lib/util/parseObjectStyles.js:21:37
[0]     at Array.flatMap (<anonymous>)
[0]     at parseObjectStyles (/home/o/Documents/js/cra-tailwind-3/node_modules/tailwindcss/lib/util/parseObjectStyles.js:20:19)
[0]     at Object.parseObjectStyles [as default] (/home/o/Documents/js/cra-tailwind-3/node_modules/tailwindcss/lib/util/parseObjectStyles.js:16:16)
[0]     at /home/o/Documents/js/cra-tailwind-3/node_modules/tailwindcss/lib/lib/setupContextUtils.js:101:64
[0]     at Array.flatMap (<anonymous>)
[0]     at parseStyles (/home/o/Documents/js/cra-tailwind-3/node_modules/tailwindcss/lib/lib/setupContextUtils.js:99:19)
[1] ℹ ｢wds｣: Project is running at http://192.168.12.1/
[1] ℹ ｢wds｣: webpack output is served from 
[1] ℹ ｢wds｣: Content not from webpack is served from /home/o/Documents/js/cra-tailwind-3/public
[1] ℹ ｢wds｣: 404s will fallback to /
[1] Starting the development server...
[1]

**Comment by mujehoxe** [comment]
needs 
npm install -D tailwindcss postcss autoprefixer
npx tailwindcss init -p
